__title__ = 'scanbuddy'
__description__ = 'Scan Buddy'
__url__ = 'https://github.com/harvard-nrg/scanbuddy'
__version__ = 'v0.3.8.1'
__author__ = 'Neuroinformatics Research Group'
__author_email__ = 'info@neuroinfo.org'
