- selector:
    series_description: regex(localizer_(Skyra_)?32ch_uncombined)
    image_type: [ORIGINAL, PRIMARY, M, ND]
  plugins:
    params:
      num_files:
        expecting: 96
      coil_elements:
        expecting: HEA;HEP
        message: CHECK HEAD COIL - make sure head coil is fully seated
    std:
      lt:
        expecting: 0.4
- selector:
    series_description: tfl_b1map_STAR
    image_type: [ORIGINAL, PRIMARY, M, ND]
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 12
      pixel_spacing:
        expecting: [4, 4]
      base_resolution:
        expecting: [0, 64, 56, 0]
      percent_phase_field_of_view:
        expecting: 87.5
      slice_thickness:
        expecting: 8
      echo_time:
        expecting: 1.83
      repetition_time:
        expecting: 8000
      coil_elements:
        expecting: HEA;HEP
      flip_angle:
        expecting: 8
      prescan_norm:
        expecting: Off
      bandwidth:
        expecting: 490
      pe_direction:
        expecting: ROW
      orientation_string:
        expecting: regex(Sag>.*)
- selector:
    series_description: RF_Sens_head
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 44
      pixel_spacing:
        expecting: [4, 4]
      base_resolution:
        expecting: [0, 64, 56, 0]
      percent_phase_field_of_view:
        expecting: 87.5
      slice_thickness:
        expecting: 4
      echo_time:
        expecting: 2
      repetition_time:
        expecting: 4.6
      coil_elements:
        expecting: HEA;HEP
      flip_angle:
        expecting: 6
      prescan_norm:
        expecting: Off
      bandwidth:
        expecting: 490
      pe_direction:
        expecting: ROW
      orientation_string:
        expecting: regex(Sag>.*)
- selector:
    series_description: RF_Sens_body
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 44
      pixel_spacing:
        expecting: [4, 4]
      base_resolution:
        expecting: [0, 64, 56, 0]
      percent_phase_field_of_view:
        expecting: 87.5
      slice_thickness:
        expecting: 4
      echo_time:
        expecting: 2
      repetition_time:
        expecting: 4.6
      coil_elements:
        expecting: BC
      flip_angle:
        expecting: 6
      prescan_norm:
        expecting: Off
      bandwidth:
        expecting: 490
      pe_direction:
        expecting: ROW
      orientation_string:
        expecting: regex(Sag>.*)
- selector:
    series_description: ABCD_T1w_MPR_vNav_setter
    image_type: [ORIGINAL, PRIMARY, M, ND]
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 32
      pixel_spacing:
        expecting: [8, 8]
      base_resolution:
        expecting: [0, 32, 32, 0]
      percent_phase_field_of_view:
        expecting: 100
      slice_thickness:
        expecting: 8
      echo_time:
        expecting: 4.8
      repetition_time:
        expecting: 11
      coil_elements:
        expecting: BC
      flip_angle:
        expecting: 2
      prescan_norm:
        expecting: Off
      bandwidth:
        expecting: 4885
      pe_direction:
        expecting: ROW
      orientation_string:
        expecting: regex(Sag>.*)
- selector:
    series_description: ABCD_T1w_MPR_vNav
    image_type: [ORIGINAL, PRIMARY, M, ND, NORM]
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 176
      pixel_spacing:
        expecting: [1, 1]
      base_resolution:
        expecting: [0, 256, 256, 0]
      percent_phase_field_of_view:
        expecting: 100
      slice_thickness:
        expecting: 1
      echo_time:
        expecting: 2.9
      repetition_time:
        expecting: 2500
      coil_elements:
        expecting: HEA;HEP
      flip_angle:
        expecting: 8
      prescan_norm:
        expecting: On
      bandwidth:
        expecting: 240
      pe_direction:
        expecting: ROW
      orientation_string:
        expecting: regex(Sag>.*)
- selector:
    series_description: ABCD_fMRI_DisMap_Skyra_PA
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 60
      pixel_spacing:
        expecting: [2.4, 2.4]
      base_resolution:
        expecting: [90, 0, 0, 90]
      percent_phase_field_of_view:
        expecting: 100
      slice_thickness:
        expecting: 2.4
      echo_time:
        expecting: 80
      repetition_time:
        expecting: 7300
      coil_elements:
        expecting: HEA;HEP
      flip_angle:
        expecting: 90
      prescan_norm:
        expecting: Off
      bandwidth:
        expecting: 2220
      pe_direction:
        expecting: COL
      orientation_string:
        expecting: regex(Tra>.*)
- selector:
    series_description: ABCD_fMRI_DisMap_Skyra_AP
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 60
      pixel_spacing:
        expecting: [2.4, 2.4]
      base_resolution:
        expecting: [90, 0, 0, 90]
      percent_phase_field_of_view:
        expecting: 100
      slice_thickness:
        expecting: 2.4
      echo_time:
        expecting: 80
      repetition_time:
        expecting: 7300
      coil_elements:
        expecting: HEA;HEP
      flip_angle:
        expecting: 90
      prescan_norm:
        expecting: Off
      bandwidth:
        expecting: 2220
      pe_direction:
        expecting: COL
      orientation_string:
        expecting: regex(Tra>.*)
- selector:
    series_description: ABCD_fMRI_rest_Skyra
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 60
      num_volumes:
        expecting: 383
      pixel_spacing:
        expecting: [2.4, 2.4]
      base_resolution:
        expecting: [90, 0, 0, 90]
      percent_phase_field_of_view:
        expecting: 100
      slice_thickness:
        expecting: 2.4
      echo_time:
        expecting: 35
      repetition_time:
        expecting: 890
      coil_elements:
        expecting: HEA;HEP
      flip_angle:
        expecting: 52
      prescan_norm:
        expecting: Off
      bandwidth:
        expecting: 2220
      pe_direction:
        expecting: COL
      orientation_string:
        expecting: regex(Tra>.*)
    volreg:
      params: null
- selector:
    series_description: ABCD_T2w_SPC_vNav_setter
    image_type: [ORIGINAL, PRIMARY, M, ND]
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 32
      pixel_spacing:
        expecting: [8, 8]
      base_resolution:
        expecting: [0, 32, 32, 0]
      percent_phase_field_of_view:
        expecting: 100
      slice_thickness:
        expecting: 8
      echo_time:
        expecting: 6.1
      repetition_time:
        expecting: 13
      coil_elements:
        expecting: BC
      flip_angle:
        expecting: 2
      prescan_norm:
        expecting: Off
      bandwidth:
        expecting: 4885
      pe_direction:
        expecting: ROW
      orientation_string:
        expecting: regex(Sag>.*)
- selector:
    series_description: ABCD_T2w_SPC_vNav
    image_type: [ORIGINAL, PRIMARY, M, ND, NORM]
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 176
      pixel_spacing:
        expecting: [1, 1]
      base_resolution:
        expecting: [0, 256, 256, 0]
      percent_phase_field_of_view:
        expecting: 100
      slice_thickness:
        expecting: 1
      echo_time:
        expecting: 565
      repetition_time:
        expecting: 3200
      coil_elements:
        expecting: HEA;HEP
      prescan_norm:
        expecting: On
      bandwidth:
        expecting: 240
      pe_direction:
        expecting: ROW
      orientation_string:
        expecting: regex(Sag>.*)
- selector:
    series_description: UKbioDiff_ABCDseq_DistMap_PA
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 72
      pixel_spacing:
        expecting: [2, 2]
      base_resolution:
        expecting: [108, 0, 0, 108]
      percent_phase_field_of_view:
        expecting: 100
      slice_thickness:
        expecting: 2
      echo_time:
        expecting: 99
      repetition_time:
        expecting: 10900
      coil_elements:
        expecting: HEA;HEP
      flip_angle:
        expecting: 90
      prescan_norm:
        expecting: Off
      bandwidth:
        expecting: 1780
      pe_direction:
        expecting: COL
      orientation_string:
        expecting: regex(Tra>.*)
- selector:
    series_description: UKbioDiff_ABCDseq_DistMap_AP
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 72
      pixel_spacing:
        expecting: [2, 2]
      base_resolution:
        expecting: [108, 0, 0, 108]
      percent_phase_field_of_view:
        expecting: 100
      slice_thickness:
        expecting: 2
      echo_time:
        expecting: 99
      repetition_time:
        expecting: 10900
      coil_elements:
        expecting: HEA;HEP
      flip_angle:
        expecting: 90
      prescan_norm:
        expecting: Off
      bandwidth:
        expecting: 1780
      pe_direction:
        expecting: COL
      orientation_string:
        expecting: regex(Tra>.*)
- selector:
    series_description: UKbioDiff_ABCDseq_ABCDdvs
  plugins:
    params:
      patient_position:
        expecting: HFS
      num_slices:
        expecting: 72
      num_volumes:
        expecting: 103
      pixel_spacing:
        expecting: [2, 2]
      base_resolution:
        expecting: [108, 0, 0, 108]
      percent_phase_field_of_view:
        expecting: 100
      slice_thickness:
        expecting: 2
      echo_time:
        expecting: 99
      repetition_time:
        expecting: 3700
      coil_elements:
        expecting: HEA;HEP
      flip_angle:
        expecting: 90
      prescan_norm:
        expecting: Off
      bandwidth:
        expecting: 1780
      pe_direction:
        expecting: COL
      orientation_string:
        expecting: regex(Tra>.*)
